apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-rest-o-rant-web
  name: rest-o-rant-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-rest-o-rant-web
  template:
    metadata:
      labels:
        app: deployment-rest-o-rant-web
    spec:
      containers:
      - image: rbroker/rest-o-rant-web:{{VERSION}}
        name: rest-o-rant-web
        ports:
        - containerPort: 80
          name: http
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: rest-o-rant-web
spec:
  ports:
  - name: apiport
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: deployment-rest-o-rant-web
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rest-o-rant-web
spec:
  rules:
  - host: {{URL}}
    http:
      paths:
      - backend:
          serviceName: rest-o-rant-web
          servicePort: 80
        path: /
        pathType: ImplementationSpecific
